spark:
    job_name: "dev-local-xwj-KernelEngine-plugin"
    master: "local"
    conf: "spark.driver.memory=2g;
           spark.executor.memory=2g;
           spark.sql.session.timeZone=CST"

minio:
    endpoint:   "http://10.57.232.167:31359"
    accessKey:  "AKIAIOSFODNN7EXAMPLE"
    secretKey:  "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    bucket:     "rca-ftp"

cockroachdb:
    adapter:    "postgresql"
    host:       "10.57.232.61"
    port:       "26257"
    sslmode:    "require"
    database:   "rca-dev"
    username:   "bigdata"
    password:   "bigdata"
    conn_str:   "jdbc:{{adapter}}://{{host}}:{{port}}/{{database}}"

mariadb:
    adapter:    "mysql"
    host:       "10.57.232.61"
    port:       "3308"
    database:   "rca-dev"
    username:   "edgeserver"
    password:   "Foxconn123654!@"
    conn_str:   "jdbc:{{adapter}}://{{host}}:{{port}}/{{database}}?useSSL=false&useUnicode=true&characterEncoding=UTF-8"

general:
    factory: "CQ"
    from_minio: "true"
    max_records_within_a_file: "5000"

part_vendor_rules:
    Label: "PARTSN,0,0"
    Body: "PARTSN,0,0"
    Bag: "PARTSN,0,0"
    Disc Valve: "PARTSN,0,0"
    Acc: "PARTSN,0,0"
    Lid: "PARTSN,0,0"
    Septum: "PARTSN,0,0"
    Ink: "PARTSN,0,0"
    Acumen Chip : "PARTSN,0,0"
    Film : "PARTSN,0,0"

part_datecode_rules:
    Label: "PARTSN,0,0"
    Body: "PARTSN,0,0"
    Bag: "PARTSN,0,0"
    Disc Valve: "PARTSN,0,0"
    Acc: "PARTSN,0,0"
    Lid: "PARTSN,0,0"
    Septum: "PARTSN,0,0"
    Ink: "PARTSN,0,0"
    Acumen Chip : "PARTSN,0,0"
    Film : "PARTSN,0,0"

local_log_path:
    data_base_path: "file:/C:/Users/foxconn/Desktop/DATA"
    wip_path: "{{data_base_path}}/r_wip_sfc_0_20190410_164427_165927_01.txt"
    wip_parts_path: "{{data_base_path}}/r_wip_parts_sfc_0_20190410_165841_171341_01.txt"
    bobcat_path: "{{data_base_path}}/F6U19-30001_bob_0_20190409_082020_082458_02.txt"
    wip_file_limits: "1"
    wip_parts_file_limits: "1"
    bobcat_file_limits: "1"

    test_detail_compression_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION/vfpa_trans_fail_list_20190513-20190520.tar.xz"
    test_detail_compression_tmp_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_TMP/"
    test_detail_compression_output_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_OUTPUT/"
    test_detail_compression_output_successful_path: "{{test_detail_compression_output_path}}/SUCCESSFUL"
    test_detail_compression_output_failed_path: "{{test_detail_compression_output_path}}/FAILED"
    #temp for validation
    test_detail_compression_output_result_path: "{{test_detail_compression_output_path}}/RESULT"


    test_detail_path: "{{data_base_path}}/RCA/ask/.txt"
    test_detail_file_limits: "1"

minio_log_path:
    #data_base_path: "s3a://rca-ftp/IPPD-L10/Data"
    data_base_path: "s3a://rca-dev/IPPD-L10/Data"
    wip_path: "{{data_base_path}}/SFC/R_WIP_SFC/"
    wip_parts_path: "{{data_base_path}}/SFC/R_WIP_PARTS_SFC/"
    bobcat_path: "{{data_base_path}}/Bobcat_D/"
    bobcat_d_tmp_path: "{{data_base_path}}/Bobcat_D_TMP/"
    bobcat_output_path: "{{data_base_path}}/Bobcat/"
    wip_file_limits: "1"
    wip_parts_file_limits: "1"
    bobcat_file_limits: "1"

    test_detail_compression_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION/"
    test_detail_compression_tmp_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_TMP/"
    test_detail_compression_output_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_OUTPUT/"
    test_detail_compression_output_successful_path: "{{test_detail_compression_output_path}}/SUCCESSFUL"
    test_detail_compression_output_failed_path: "{{test_detail_compression_output_path}}/FAILED"
    #temp for validation
    test_detail_compression_output_result_path: "{{test_detail_compression_output_path}}/RESULT"

    test_detail_path: "{{data_base_path}}/TEST_DETAIL"
    test_detail_file_limits: "1"

summary_log_path:
    data_base_path: "s3a://test"
    tag: "KE"
    file_extension: "log"
    job_fmt: "yyyy-MM-dd HH:mm:ss"

log_prop:
    #CN8BJ7C2G1_||_CN8BJ7C2G1_||_296200140_||_V1N03B#629_||_V1N03B#629_||_Main   B_||_2018-11-19 13:39:07.467_||__||__||_TaiJi   Base_||_D626
    wip_col: "id,sn,wo,hh_part,cust_part,assembline,scantime,na1,na2,product,floor"
    wip_table: "part_master"
    wip_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN8BJ7C2G1_||_C189220M8PFAC_||_2018-11-19 13:39:07.467_||_F1034891_||_Main B_||_LK_||_F5S43-60001_||_F5S43-60001_||_D626_||_0
    wip_parts_col: "id,partsn,scantime,opid,assembly_station,part,hh_pard,cust_part,line,disassembly"
    wip_parts_table: "part_detail"
    wip_parts_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN8BS7C334_||_TLEOL_||_TLEOL_||_LC_TLEOL_41_||_11/29/2018 8:33:10 AM_||_11/29/2018 8:38:46 AM_||_0_||__||__||_11/29/2018 8:38:46 AM
    bobcat_col: "sn,station,stationcode,machine,start_time,end_time,istestfail,symptom,desc_,uploadtime,c1,c2,c3"
    bobcat_table: "test"
    bobcat_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN95I870ZC06MD_||_SOR_||_SOR_||_CN95I870ZC06MD_||_L7_TLEOL_06_||_Exception_||_2019/05/18 06:36_||_2019/05/18 06:36_||_PcaVerifyFirmwareRev_||_Error_||_MP_||__||_CQ_||_D62_||_2_||_ProcPCClockSync^DResultInfo^APcaVerifyFirmwareRev^DResultInfo^APcaVerifyFirmwareRev^DExpectedVersion^APcaVerifyFirmwareRev^DReadVersion^APcaVerifyFirmwareRev^DDateTimeStarted^APcaVerifyFirmwareRev^DActualFWUpdate^APcaVerifyFirmwareRev^DFWUpdateDSIDFirst_||_ProcPCClockSync^DResultInfo^C^APcaVerifyFirmwareRev^DResultInfo^C^APcaVerifyFirmwareRev^DExpectedVersion^C^APcaVerifyFirmwareRev^DReadVersion^C^APcaVerifyFirmwareRev^DDateTimeStarted^C5/18/2019 5:29:48 AM^APcaVerifyFirmwareRev^DActualFWUpdate^C^APcaVerifyFirmwareRev^DFWUpdateDSIDFirst^C_||_ProcPCClockSync^DResultInfo^C^APcaVerifyFirmwareRev^DResultInfo^C^APcaVerifyFirmwareRev^DExpectedVersion^C^APcaVerifyFirmwareRev^DReadVersion^C^APcaVerifyFirmwareRev^DDateTimeStarted^C^APcaVerifyFirmwareRev^DActualFWUpdate^C^APcaVerifyFirmwareRev^DFWUpdateDSIDFirst^C_||_ProcPCClockSync^DResultInfo^C^APcaVerifyFirmwareRev^DResultInfo^C^APcaVerifyFirmwareRev^DExpectedVersion^C^APcaVerifyFirmwareRev^DReadVersion^CTJP1FN1845AR^APcaVerifyFirmwareRev^DDateTimeStarted^C^APcaVerifyFirmwareRev^DActualFWUpdate^C169^APcaVerifyFirmwareRev^DFWUpdateDSIDFirst^C_||_ProcPCClockSync^DResultInfo^C^APcaVerifyFirmwareRev^DResultInfo^C^APcaVerifyFirmwareRev^DExpectedVersion^C^APcaVerifyFirmwareRev^DReadVersion^CTJP1FN1845AR^APcaVerifyFirmwareRev^DDateTimeStarted^C^APcaVerifyFirmwareRev^DActualFWUpdate^C169^APcaVerifyFirmwareRev^DFWUpdateDSIDFirst^C_||_2019/05/18 06:36_||_2019/05/18 06:36_||_TLEOL_||_2019/05/18 06:36_||_TaiJi Base_||_42.3.8 REV_37_Taiji25
    test_detail_col: "sn,build_name,build_description,unit_number,station_id,test_status,test_starttime,test_endtime,list_of_failure,list_of_failure_detail,test_phase,machine_id,factory_code,floor,line_id,test_item,test_value,test_unit,test_lower,test_upper,create_time,update_time,station_name,start_date,product,test_version"
    test_detail_table: "test_detail"
    test_detail_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    log_seperator: "_\\|\\|_"
    log_seperator_non_escape: "_||_"

analysis:
    fail_condition: "1"

test_floor_line:
    code_5: "D713"
    code_D714: "D714"
    code_T: "D721"
    code_4: "D722"
    code_6: "D723"
    code_F: "D621"
    code_7: "D622"
    code_B: "D623"
    code_9: "D624"
    code_8: "D625"
    code_C: "D626"
    code_G: "D631"
    code_H: "D632"
    code_Q: "D633"
    code_N: "D634"
    code_P: "D635"
    code_D: "D636"

taiji_base:
    code: "06MD,06PK,06PN,06P4,06PP,06PS,06PT,06PV,06PX,06PY,06PZ,06Q2,06Q3,06Q4,06Q7,06Q8,06Q9,06QD,070W,070X"

